### PR TITLE
Support Sauce Labs on PRs

### PR DESCRIPTION
**Pull request by halkeye**
@nolanlawson I couldn't figure out your sauce_username so I just put a placeholder for now.

this should work for pull requests though if you are okay with exposing that info (though I suspect the branch-only-master will prevent prs too?)

### CODE REVIEW

**Comment by halkeye** [comment]
oh wow, it totally still runs for PRs

yea, if we can get the username in there, it should test every PR

**Comment by nolanlawson** [comment]
I need to take a second look at this and get everything working. Putting it on my TODO list, thanks for the PR!

**Comment by halkeye** [comment]
<3

the only thing that i think needs changing is:

`SAUCE_USERNAME=yourusername`

**Comment by nolanlawson** [comment]
On second thought, I would prefer not to merge this because the current behavior is that every run against SauceLabs also writes the results to my personal Cloudant database, and I'd rather not allow random people to be able to append to it, because currently I don't have a way to remove data; it only grows over time. So thanks a bunch for the PR; I'll probably use it on other projects but for this one the current behavior is okay.

**Comment by halkeye** [comment]
In the PR mode, the cloudant's won't be defined, so it won't actually write
to your db

but yea, thats cool too man :D

**Pull request closed without merging**
